#include "voice.h"

/*
 * Voice interaction module I2C protocol
 *
 * Pins are generated by SysConfig:
 *   I2C_0 SDA: PA28
 *   I2C_0 SCL: PA31
 *
 * Protocol documents:
 *   - default 7-bit I2C address: 0x34
 *   - optional new-version address: 0x33
 *   - result register: 0x64, read 1 byte
 *   - speak register: 0x6E, write 2 bytes: type, id
 *   - address register: 0x03, write 1 byte: 0x33 or 0x34
 */
#define VOICE_I2C_ADDR_DEFAULT      0x34
#define VOICE_I2C_ADDR_ALTERNATE    0x33

#define VOICE_REG_SET_ADDR          0x03
#define VOICE_REG_RESULT            0x64
#define VOICE_REG_SPEAK             0x6E

#define VOICE_SPEAK_TYPE_COMMAND    0x00
#define VOICE_SPEAK_TYPE_NORMAL     0xFF

#define VOICE_I2C_TIMEOUT           10000000
#define VOICE_ADDR_SWITCH_DELAY     3200000

static uint8_t g_voiceAddr = VOICE_I2C_ADDR_DEFAULT;
static uint8_t g_voiceReady = 0;


static void UART_SendChar(char ch)
{
    DL_UART_Main_transmitData(UART_0_INST, ch);

    while(DL_UART_isBusy(UART_0_INST));
}


static void UART_SendString(char *str)
{
    while(*str)
    {
        UART_SendChar(*str++);
    }
}


static void UART_SendHex(uint8_t data)
{
    char buf[3];
    const char table[] = "0123456789ABCDEF";

    buf[0] = table[(data >> 4) & 0x0F];
    buf[1] = table[data & 0x0F];
    buf[2] = '\0';

    UART_SendString(buf);
}


static void UART_SendHex32(uint32_t data)
{
    uint8_t i;
    const char table[] = "0123456789ABCDEF";

    UART_SendString("0x");

    for(i = 0; i < 8; i++)
    {
        UART_SendChar(table[(data >> 28) & 0x0F]);
        data <<= 4;
    }
}


static void Voice_I2C_PrintStatus(char *tag, uint32_t status)
{
    UART_SendString(tag);
    UART_SendString(" MSR=");
    UART_SendHex32(status);

    if(status & DL_I2C_CONTROLLER_STATUS_ADDR_ACK)
    {
        UART_SendString(" ADDR_NACK");
    }

    if(status & DL_I2C_CONTROLLER_STATUS_DATA_ACK)
    {
        UART_SendString(" DATA_NACK");
    }

    if(status & DL_I2C_CONTROLLER_STATUS_ARBITRATION_LOST)
    {
        UART_SendString(" ARB_LOST");
    }

    UART_SendString("\r\n");
}


static void Voice_I2C_Recover(void)
{
    DL_I2C_resetControllerTransfer(I2C_0_INST);
    DL_I2C_flushControllerTXFIFO(I2C_0_INST);
    DL_I2C_flushControllerRXFIFO(I2C_0_INST);
}


static uint8_t Voice_I2C_WaitIdle(void)
{
    uint32_t timeout = VOICE_I2C_TIMEOUT;

    while(!(DL_I2C_getControllerStatus(I2C_0_INST)
            & DL_I2C_CONTROLLER_STATUS_IDLE))
    {
        timeout--;

        if(timeout == 0)
        {
            UART_SendString("I2C IDLE TIMEOUT\r\n");
            Voice_I2C_Recover();
            return 0;
        }
    }

    return 1;
}


static uint8_t Voice_I2C_WaitTransferDone(char *tag)
{
    uint32_t timeout = VOICE_I2C_TIMEOUT;
    uint32_t status;

    while(DL_I2C_getControllerStatus(I2C_0_INST)
          & DL_I2C_CONTROLLER_STATUS_BUSY_BUS)
    {
        timeout--;

        if(timeout == 0)
        {
            UART_SendString(tag);
            UART_SendString(" TIMEOUT\r\n");
            Voice_I2C_Recover();
            return 0;
        }
    }

    status = DL_I2C_getControllerStatus(I2C_0_INST);

    if(status & DL_I2C_CONTROLLER_STATUS_ERROR)
    {
        Voice_I2C_PrintStatus(tag, status);
        Voice_I2C_Recover();
        return 0;
    }

    return Voice_I2C_WaitIdle();
}


static uint8_t Voice_I2C_WriteReg(uint8_t addr, uint8_t reg,
        uint8_t *data, uint8_t len)
{
    uint8_t txBuf[3];
    uint8_t i;

    if(len > 2)
    {
        return 0;
    }

    if(!Voice_I2C_WaitIdle())
    {
        return 0;
    }

    DL_I2C_flushControllerTXFIFO(I2C_0_INST);
    DL_I2C_flushControllerRXFIFO(I2C_0_INST);

    txBuf[0] = reg;

    for(i = 0; i < len; i++)
    {
        txBuf[i + 1] = data[i];
    }

    DL_I2C_fillControllerTXFIFO(I2C_0_INST, txBuf, (uint8_t)(len + 1));

    DL_I2C_startControllerTransfer(
            I2C_0_INST,
            addr,
            DL_I2C_CONTROLLER_DIRECTION_TX,
            (uint16_t)(len + 1));

    return Voice_I2C_WaitTransferDone("I2C TX");
}


static uint8_t Voice_I2C_ReadReg(uint8_t addr, uint8_t reg,
        uint8_t *data, uint8_t len)
{
    uint8_t i;
    uint32_t timeout;

    if(len == 0)
    {
        return 0;
    }

    if(!Voice_I2C_WaitIdle())
    {
        return 0;
    }

    DL_I2C_flushControllerTXFIFO(I2C_0_INST);
    DL_I2C_flushControllerRXFIFO(I2C_0_INST);

    DL_I2C_fillControllerTXFIFO(I2C_0_INST, &reg, 1);

    DL_I2C_startControllerTransfer(
            I2C_0_INST,
            addr,
            DL_I2C_CONTROLLER_DIRECTION_TX,
            1);

    if(!Voice_I2C_WaitTransferDone("I2C REG"))
    {
        return 0;
    }

    DL_I2C_startControllerTransfer(
            I2C_0_INST,
            addr,
            DL_I2C_CONTROLLER_DIRECTION_RX,
            len);

    for(i = 0; i < len; i++)
    {
        timeout = VOICE_I2C_TIMEOUT;

        while(DL_I2C_isControllerRXFIFOEmpty(I2C_0_INST))
        {
            timeout--;

            if(timeout == 0)
            {
                UART_SendString("I2C RX TIMEOUT\r\n");
                Voice_I2C_Recover();
                return 0;
            }

            if(DL_I2C_getControllerStatus(I2C_0_INST)
               & DL_I2C_CONTROLLER_STATUS_ERROR)
            {
                Voice_I2C_PrintStatus("I2C RX",
                        DL_I2C_getControllerStatus(I2C_0_INST));
                Voice_I2C_Recover();
                return 0;
            }
        }

        data[i] = DL_I2C_receiveControllerData(I2C_0_INST);
    }

    return Voice_I2C_WaitTransferDone("I2C RX DONE");
}


static uint8_t Voice_ProbeAddress(uint8_t addr)
{
    uint8_t value;

    return Voice_I2C_ReadReg(addr, VOICE_REG_RESULT, &value, 1);
}


uint8_t Voice_ClearCommand(void)
{
    uint8_t value = VOICE_CMD_NONE;

    if(!g_voiceReady)
    {
        return 0;
    }

    return Voice_I2C_WriteReg(g_voiceAddr, VOICE_REG_RESULT, &value, 1);
}


static uint8_t Voice_FindAddress(void)
{
    if(Voice_ProbeAddress(VOICE_I2C_ADDR_DEFAULT))
    {
        g_voiceAddr = VOICE_I2C_ADDR_DEFAULT;
        return 1;
    }

    if(Voice_ProbeAddress(VOICE_I2C_ADDR_ALTERNATE))
    {
        g_voiceAddr = VOICE_I2C_ADDR_ALTERNATE;
        return 1;
    }

    return 0;
}


void Voice_Init(void)
{
    UART_SendString("VOICE INIT\r\n");
    UART_SendString("I2C0 SDA=PA28 SCL=PA31\r\n");

    Voice_I2C_Recover();
    delay_cycles(VOICE_ADDR_SWITCH_DELAY);

    g_voiceReady = Voice_FindAddress();

    if(g_voiceReady)
    {
        UART_SendString("VOICE ADDR = ");
        UART_SendHex(g_voiceAddr);
        UART_SendString("\r\n");
    }
    else
    {
        UART_SendString("VOICE NOT FOUND\r\n");
    }
}


uint8_t Voice_ReadCommand(void)
{
    uint8_t result = VOICE_CMD_NONE;

    if(!g_voiceReady)
    {
        g_voiceReady = Voice_FindAddress();

        if(!g_voiceReady)
        {
            return VOICE_CMD_NONE;
        }
    }

    if(!Voice_I2C_ReadReg(g_voiceAddr, VOICE_REG_RESULT, &result, 1))
    {
        g_voiceReady = 0;
        return VOICE_CMD_NONE;
    }

    if(result != VOICE_CMD_NONE)
    {
        UART_SendString("VOICE RESULT = ");
        UART_SendHex(result);
        UART_SendString("\r\n");
        Voice_ClearCommand();
    }

    return result;
}


uint8_t Voice_SpeakCommand(uint8_t id)
{
    uint8_t data[2];

    if(!g_voiceReady)
    {
        return 0;
    }

    data[0] = VOICE_SPEAK_TYPE_COMMAND;
    data[1] = id;

    return Voice_I2C_WriteReg(g_voiceAddr, VOICE_REG_SPEAK, data, 2);
}


uint8_t Voice_SpeakNormal(uint8_t id)
{
    uint8_t data[2];

    if(!g_voiceReady)
    {
        return 0;
    }

    data[0] = VOICE_SPEAK_TYPE_NORMAL;
    data[1] = id;

    return Voice_I2C_WriteReg(g_voiceAddr, VOICE_REG_SPEAK, data, 2);
}


uint8_t Voice_SetAddress(uint8_t newAddr)
{
    uint8_t data = newAddr;

    if((newAddr != VOICE_I2C_ADDR_DEFAULT)
       && (newAddr != VOICE_I2C_ADDR_ALTERNATE))
    {
        return 0;
    }

    if(!g_voiceReady)
    {
        return 0;
    }

    if(!Voice_I2C_WriteReg(g_voiceAddr, VOICE_REG_SET_ADDR, &data, 1))
    {
        return 0;
    }

    delay_cycles(VOICE_ADDR_SWITCH_DELAY);
    g_voiceAddr = newAddr;
    g_voiceReady = Voice_ProbeAddress(g_voiceAddr);

    return g_voiceReady;
}
